[package]
name = "lndk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.2"
futures = "0.3.26"
lightning = "0.0.114"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread"] }
tonic_lnd = "0.5.1"
